# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

platform :android do
  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  end

  desc "Deploy a new version to the  Firebase App Distributes"
  lane :distribute do
    firebase_token = ENV["FIREBASE_TOKEN"]
    firebase_app_distribution(
        firebase_token: firebase_token,
        app: "1:967761019225:android:7da7df5d6d49b944a64c48",
        testers: "cicd-test",
        apk_path: "build/app/outputs/flutter-apk/app-release.apk",
        release_notes: "Lots of amazing new features to test out!"
    )
  end
end

platform :ios do
  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do

  end

  desc "Deploy a new version to the Firebase App Distributes"
  lane :distribute do
    firebase_token = ENV["FIREBASE_TOKEN"]
    firebase_app_distribution(
        firebase_token: firebase_token,
        app: "1:967761019225:ios:9839a54200071d2aa64c48",
        testers: "cicd-test",
        ipa_path: "build/ios/iphoneos/Runner.app",
        release_notes: "Lots of amazing new features to test out!"
    )
  end
end