# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  end

  desc "Deploy a new version to the  Firebase App Distributes"
  lane :deploy do

  end
end

platform :ios do
  desc "Runs all the tests"
  lane :test do

  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do

  end

  desc "Deploy a new version to the Firebase App Distributes"
  lane :deploy do

  end
end