# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

platform :android do
  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    UI.message("beta")
  end

  desc "Deploy a new version to the  Firebase App Distributes"
  lane :distribute do
    firebase_token = ENV["FIREBASE_TOKEN"]
    firebase_app_distribution(
        firebase_cli_token: firebase_token,
        app: "1:967761019225:android:7da7df5d6d49b944a64c48",
        groups: "cicd-test",
        apk_path: "build/app/outputs/flutter-apk/app-release.apk",
        release_notes: "Lots of amazing new features to test out!"
    )
  end
end

platform :ios do
  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    UI.message("beta")
  end

  desc "Build IPA method Development"
  lane :build_ipa_development do
    gym(
      workspace: "ios/Runner.xcworkspace",
      export_method: "development",
      output_name: "Runner",
      output_directory: "ios/build",
    )
  end

  desc "Deploy a new version to the Firebase App Distributes"
  lane :distribute do
    firebase_token = ENV["FIREBASE_TOKEN"]
    firebase_app_distribution(
        firebase_cli_token: firebase_token,
        app: "1:967761019225:ios:9839a54200071d2aa64c48",
        groups: "cicd-test",
        ipa_path: "ios/build/Runner.ipa",
        release_notes: "Lots of amazing new features to test out!"
    )
  end
end