# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: CI/CD

on:
  push:
    branches: [ "config/1-fastlane" ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      
      - name: Unit Test
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.13.0'
          architecture: x64
      - run: flutter pub get
      - run: flutter test
      
      - name: Build iOS
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.13.0'
          architecture: x64
      - run: flutter pub get
      - run: flutter build ios --release --no-codesign
      
      - name: Build Android
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.13.0'
          architecture: x64
      - run: flutter pub get
      - run: flutter build apk
